# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SimpleCamMapExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleCamMapExample
  pod 'SnapKit', '~> 4.0.0'
  pod 'CamMap', :path => '~/Documents/Libraries/CamMap'

end
